# Grappling With Being

## What is Existing?

## What is not Existing?

Is there any "thing" which does not exist? I exist, of course. And the perceivable things around me exist, and the air exists, and the invisible radio waves exist, and the space-time through which light travels exists. Do thoughts exist?

I perceive thoughts - the nature of what exactly they are and where they come from may be up to debate, but my thoughts certainly exist. Ending thought actually seems strangely difficult. Most people have an ongoing inner monologue and a mind's eye. Try temporarily switching off these faculties. If that doesn't work out, try avoiding uncomfortable thoughts. It's not easy. Even in deep meditation, unwelcome thoughts seem to bubble up. Am I truly creating these thoughts? Where do these thoughts come from? Perhaps thoughts do possess some sort of primordial existence and I am simply uncovering them? In the same way an archaeologist digs up fossils, or as a mathematician "solves" an equation, it seems possible for thoughts to exist even when I am not thinking of them. 

### Additional questions:

Does a concept have an existence? Whatever does not exist - does the potential for its existence exist? Does potential for existence necessitate existence?

## What is Being?

Being is experiencing existence, regardless of whether that existence is material or immaterial. Notice the distinction between Being and merely Existing. A rock exists, but the rock is not Being unless it has some sense of experience.

### Additional questions:

What is Experiencing? What is Existing?

## What is not Being?

## Being through Time

### Additional questions:

Does the past still exist? Does the future exist? What does this say about free will?

## To be, or not to be..

By all accounts, Being seems not to be a choice. I was brought into this world not of my own volition but by someone or something else's will. On the other hand, whether the continuity of being is a choice seems quite a different question. 

### Additional questions:

Can I stop Being? Can I end my sense of experience? Would I be able to pick it up again some day?

## What is awareness?

## I should not Exist

A conundrum facing physicists is the problem of the apparent fine-tuning of the universe. There are several physical constants (e.g. the speed of light, the force of gravity, the ratio of matter to anti-matter) which govern the cosmos. If any of these constants were just slightly off, the universe would not be able to harbor life. The chance of these numbers being so precisely on target is infitesimally small - so small, that physicists have put forward the multiverse theory as a potential solution. The existence of a multiverse consisting of a huge quantity of universes with distinct physical laws could allow just a small proportion of universes to harbor life.

A conundrum facing the individual is the seeming improbability of the chain of events leading up to their Being. I ask myself: how likely was it for every bit of energy and every particle of matter to form and move and interact in exactly the way that would lead to my present-day existence? For life to have developed, for the dinosaurs to have risen and fallen, for mammals to overtake the earth, for sentient human beings to develop tools and language and agriculture, for particular civilizations to rise and fall, for just the right two people to meet so that just the right egg to be fertilized by just the right sperm so that a physical body may form with exactly the features and systems with which I identify.. the probability is 0. So it would seem I won the lottery of all lotteries. Does that imply there were lottery losers who do not exist? 

Indeed, I seem to be attached to only this body. I am not a single atom, a protein, a cell, nor a tissue. And I not multiple humans simultaneously, a city, a country, nor a planet. Why does my sense of "I" rest at this juncture?

Perhaps the approach toward time and causality is incorrect. Start with "I am" and work backwards. Because I am, the universe must also be. There could be many univereses like it, but this one is mine. What might this mean about the nature of my self? Am I the reason the universe exists? Is it all for me?

## No one else should exist

If my host universe exists entirely for me, then what does that say about the other residents? Perhaps they are illusions or metaphors to help me make sense of some complex underlying truths. Perhaps they are phantoms in the sense that each them has their own plane of existence and we are somehow still able to interact. Perhaps they are a part of me to which I do not have conscious access.

### Additional questions:

What caused the big bang? Why anything at all?
